### ISSUE TITLE
how do you change the country code +91?

### ISSUE THREAD

**Issue by angledarknet** [Piyushhbhutoria/whatsappWebAPI#11]
Hello,
I am not from India, how can I change my country code +91 to my country code?
Thanks

**Comment by Piyushhbhutoria** [comment]
you need to update your country code in these lines
https://github.com/Piyushhbhutoria/whatsappWebAPI/blob/38ef5a86f0437625e322abf54c126fc108df1e46/image.go#L21
https://github.com/Piyushhbhutoria/whatsappWebAPI/blob/38ef5a86f0437625e322abf54c126fc108df1e46/text.go#L12
