### ISSUE TITLE
 cannot unmarshal array into Go value of type map[string]interface {}

### ISSUE THREAD

**Issue by tarunhv** [Piyushhbhutoria/whatsappWebAPI#6]
On running the binary getting this error 

Enter your number: **********(Number)
Logging in -> **********(Number)
panic: Error logging in:
error during login: error decoding login resp: json: cannot unmarshal array into Go value of type map[string]interface {}

**Comment by Piyushhbhutoria** [comment]
Please try again and check if this error is fixed.
