### ISSUE TITLE
Error  image upload failed: upload responsed with %!d(float64=404)

### ISSUE THREAD

**Issue by mapodesta** [Piyushhbhutoria/whatsappWebAPI#8]
Hi @Piyushhbhutoria  , i'm trying to send text,numb,and images with flags...so i send all functions in 'main.go' and when i triend to send images i've the error : 

 image upload failed: upload responsed with %!d(float64=404)

any idea?

it's the same code,the difference is im send the text numb and images wih flags...if you want i shared the code..

thanks !!

**Comment by Piyushhbhutoria** [comment]
Can you provide the steps to reproduce? Also, it will help if you can link me to the actual image. (Here or maybe e-mail as you wish)🙂

**Comment by mapodesta** [comment]
Yes, I'm copy 'text.go' 'whatsapp.go' 'schema.go' and 'image.go' in main.go ....make 'go build main.go'
in the code i'm used flags, so when you start the program you can use "./main '-word=the text' '-numb= the receiver' '-opc=1 or 2(text o image)' ....but with images doesn't work

[wsp.zip](https://github.com/Piyushhbhutoria/whatsappWebAPI/files/4711172/wsp.zip)

**Comment by mapodesta** [comment]
can you send me your e-mail ? thank for all !!!!

**Comment by Piyushhbhutoria** [comment]
> can you send me your e-mail ? thank for all !!!!

piyush.bhutoria98@gmail.com

**Comment by Piyushhbhutoria** [comment]
This will be automatically fixed with new release of [go-whatsapp](https://github.com/Rhymen/go-whatsapp). 
**A temporary fix** is manually downloading [go-whatsapp master branch](https://github.com/Rhymen/go-whatsapp) and removing `go.mod` & `go.sum` and building on your own.
